"""add webhook events

Revision ID: 0a2075552a45
Revises: 979857f3c572
Create Date: 2026-09-30 02:14:09.798223

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '0a2075552a45'
down_revision: Union[str, Sequence[str], None] = '979857f3c572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
