"""add bookings

Revision ID: 0b3abfe67a78
Revises: ccec565bda36
Create Date: 2026-09-30 01:55:12.499564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3abfe67a78'
down_revision: Union[str, Sequence[str], None] = 'ccec565bda36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('centre_test_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_at', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['centre_test_id'], ['centre_tests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_appointment_at'), 'bookings', ['appointment_at'], unique=False)
    op.create_index(op.f('ix_bookings_centre_test_id'), 'bookings', ['centre_test_id'], unique=False)
    op.create_index(op.f('ix_bookings_patient_id'), 'bookings', ['patient_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_patient_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_centre_test_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_appointment_at'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
