"""add diagnostic centres and tests

Revision ID: ccec565bda36
Revises: 4ebc9df0455f
Create Date: 2026-09-30 01:49:28.049460

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'ccec565bda36'
down_revision: Union[str, Sequence[str], None] = '4ebc9df0455f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
