import { useState } from "react";
import { Link, useLocation } from "react-router-dom";
import api from "../lib/api";
import { useApi } from "../hooks/useApi";
import { DataTable, PageHeader } from "../components/Layout";

const money=(v)=>`₹${Number(v||0).toLocaleString("en-IN")}`;
const pretty=(v)=>v?.replaceAll("_"," ")||"—";

export default function AdminWorkspace(){
  const path=useLocation().pathname;
  if(path==="/admin/centres") return <CentresAdmin/>;
  if(path==="/admin/tests") return <TestsAdmin/>;
  if(path==="/admin/users") return <UsersAdmin/>;
  if(path==="/admin/bookings") return <BookingsAdmin/>;
  if(path==="/admin/audit") return <AuditAdmin/>;
  if(path==="/admin/notifications") return <NotificationsAdmin/>;
  return <OverviewAdmin/>;
}

function OverviewAdmin(){
  const {data,loading,error}=useApi("/admin/overview");
  const {items:bookings}=useApi("/admin/bookings?limit=12");
  const {items:centres}=useApi("/admin/centres?limit=6");
  const statuses=data?.bookings_by_status||{};
  const total=Object.values(statuses).reduce((a,b)=>a+b,0)||1;
  return <><PageHeader eyebrow="PLATFORM ADMINISTRATION" title="Platform overview" subtitle="Monitor EVE Healthcare and manage the care network."/><div className="metric-grid admin-metrics">{[["◉","Users",data?.users],["⌖","Diagnostic centres",data?.centres],["✚","Diagnostic tests",data?.tests],["▦","Total bookings",data?.bookings]].map(([icon,label,value])=><Metric key={label} icon={icon} label={label} value={loading?"—":value??0}/>)}</div>{error&&<div className="notice error">{error}</div>}<div className="admin-grid"><section className="panel chart-panel"><div className="section-title"><div><p className="eyebrow">BOOKING HEALTH</p><h2>Booking status</h2></div><Link className="subtle-link" to="/admin/bookings">All bookings →</Link></div><div className="status-bars">{[["confirmed","Confirmed","#0b9a72"],["pending","Pending","#e4a84b"],["payment_failed","Payment failed","#d87570"],["cancelled","Cancelled","#9da9a3"],["completed","Completed","#6595c6"]].map(([key,label,color])=><div className="status-bar-row" key={key}><span>{label}</span><div className="status-bar-track"><i style={{width:`${Math.round((statuses[key]||0)*100/total)}%`,background:color}}/></div><b>{statuses[key]||0}</b></div>)}</div></section><section className="panel"><div className="section-title"><div><p className="eyebrow">NETWORK</p><h2>Active centres</h2></div><Link className="subtle-link" to="/admin/centres">Manage →</Link></div><div className="admin-centre-list">{centres.map(c=><div key={c.id}><span className="round-icon">⌖</span><b>{c.name}</b><small>{c.city}</small></div>)}</div>{!centres.length&&<p className="muted">Add your first diagnostic centre.</p>}</section></div><section className="panel dashboard-panel"><div className="section-title"><div><p className="eyebrow">LATEST ACTIVITY</p><h2>Recent bookings</h2></div><Link className="subtle-link" to="/admin/bookings">View all →</Link></div><DataTable columns={[{key:"id",label:"Booking",render:(b)=>b.id.slice(0,8)},{key:"patient_id",label:"Patient",render:(b)=>b.patient_id.slice(0,8)},{key:"appointment_at",label:"Appointment",render:(b)=>new Date(b.appointment_at).toLocaleString()},{key:"amount",label:"Amount",render:(b)=>money(b.amount)},{key:"status",label:"Status",render:(b)=><span className={`status-pill status-${b.status}`}>{pretty(b.status)}</span>}]} rows={bookings} empty="No bookings have been created."/></section></>;
}
function Metric({icon,label,value}){return <article className="metric-card"><span className="metric-icon">{icon}</span><div><small>{label}</small><b>{value}</b></div></article>;}

function CentresAdmin(){
  const [refresh,setRefresh]=useState(0); const [message,setMessage]=useState("");
  const {items:centres,loading}=useApi("/admin/centres?limit=100",refresh);
  const [form,setForm]=useState({name:"",address:"",city:"",state:"",postal_code:"",phone:"",email:"",description:"",services:""});
  const create=async(e)=>{e.preventDefault();try{await api.post("/centres",{...form,services:form.services.split(",").map((x)=>x.trim()).filter(Boolean)});setForm({name:"",address:"",city:"",state:"",postal_code:"",phone:"",email:"",description:"",services:""});setMessage("Centre created.");setRefresh(refresh+1);}catch(err){setMessage(err.response?.data?.detail||"Could not create centre.");}};
  const toggle=async(c)=>{try{await api.patch(`/centres/${c.id}`,{is_active:!c.is_active});setRefresh(refresh+1);}catch(err){setMessage(err.response?.data?.detail||"Could not update centre.");}};
  return <><PageHeader eyebrow="NETWORK MANAGEMENT" title="Diagnostic centres" subtitle="Create, review and safely deactivate centres."/><section className="panel admin-form-panel"><h2>Add a centre</h2><form className="admin-form-grid" onSubmit={create}>{[["name","Centre name"],["address","Street address"],["city","City"],["state","State"],["postal_code","Postal code"],["phone","Phone"],["email","Email"],["services","Services (comma separated)"]].map(([key,label])=><label key={key}>{label}<input value={form[key]} onChange={(e)=>setForm({...form,[key]:e.target.value})} required={["name","address","city"].includes(key)}/></label>)}<label className="wide-field">Description<textarea value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></label><button className="primary-button">Create centre</button>{message&&<span className="muted">{message}</span>}</form></section><section className="panel dashboard-panel"><div className="section-title"><h2>All centres <small>{centres.length}</small></h2></div>{loading?<p>Loading centres…</p>:<DataTable columns={[{key:"name",label:"Centre"},{key:"city",label:"Location",render:(c)=>`${c.city}${c.state?`, ${c.state}`:""}`},{key:"phone",label:"Phone"},{key:"services",label:"Services",render:(c)=>(c.services||[]).join(", ")||"—"},{key:"is_active",label:"Status",render:(c)=><span className={`status-pill ${c.is_active?"status-confirmed":"status-cancelled"}`}>{c.is_active?"Active":"Inactive"}</span>},{key:"action",label:"",render:(c)=><button className="text-button" onClick={()=>toggle(c)}>{c.is_active?"Deactivate":"Activate"}</button>}]} rows={centres} empty="No centres have been added."/>}</section></>;
}

function TestsAdmin(){
  const [refresh,setRefresh]=useState(0);const [message,setMessage]=useState("");const {items:tests}=useApi("/admin/tests?limit=100",refresh);
  const [form,setForm]=useState({name:"",category:"",description:"",preparation_instructions:"",sample_type:"",duration_minutes:30,estimated_report_time_minutes:""});
  const create=async(e)=>{e.preventDefault();try{await api.post("/tests",{...form,duration_minutes:Number(form.duration_minutes),estimated_report_time_minutes:form.estimated_report_time_minutes?Number(form.estimated_report_time_minutes):null});setMessage("Test added to catalogue.");setRefresh(refresh+1);}catch(err){setMessage(err.response?.data?.detail||"Could not create test.");}};
  const toggle=async(t)=>{try{await api.patch(`/tests/${t.id}`,{is_active:!t.is_active});setRefresh(refresh+1);}catch(err){setMessage(err.response?.data?.detail||"Could not update test.");}};
  return <><PageHeader eyebrow="CATALOGUE MANAGEMENT" title="Diagnostic tests" subtitle="Maintain test descriptions, preparation and sample information."/><section className="panel admin-form-panel"><h2>Add a diagnostic test</h2><form className="admin-form-grid" onSubmit={create}>{[["name","Test name"],["category","Category"],["sample_type","Sample type"],["duration_minutes","Collection duration (minutes)"],["estimated_report_time_minutes","Report time (minutes)"],["preparation_instructions","Preparation instructions"]].map(([key,label])=><label key={key}>{label}<input value={form[key]} type={key.includes("minutes")?"number":"text"} onChange={(e)=>setForm({...form,[key]:e.target.value})} required={key==="name"}/></label>)}<label className="wide-field">Description<textarea value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></label><button className="primary-button">Add test</button>{message&&<span className="muted">{message}</span>}</form></section><section className="panel dashboard-panel"><DataTable columns={[{key:"name",label:"Test"},{key:"category",label:"Category"},{key:"sample_type",label:"Sample"},{key:"duration_minutes",label:"Duration",render:(t)=>`${t.duration_minutes} min`},{key:"is_active",label:"Status",render:(t)=><span className={`status-pill ${t.is_active?"status-confirmed":"status-cancelled"}`}>{t.is_active?"Active":"Inactive"}</span>},{key:"action",label:"",render:(t)=><button className="text-button" onClick={()=>toggle(t)}>{t.is_active?"Deactivate":"Activate"}</button>}]} rows={tests} empty="No tests yet."/></section></>;
}

function UsersAdmin(){
  const [refresh,setRefresh]=useState(0);const [query,setQuery]=useState("");const [message,setMessage]=useState("");const {items:users}=useApi(`/admin/users?limit=100${query?`&q=${encodeURIComponent(query)}`:""}`,refresh);const {items:centres}=useApi("/admin/centres?limit=100");
  const [centreId,setCentreId]=useState("");const [email,setEmail]=useState("");
  const assign=async(e)=>{e.preventDefault();try{await api.post(`/centres/${centreId}/staff`,{email});setEmail("");setMessage("Centre staff member assigned.");setRefresh(refresh+1);}catch(err){setMessage(err.response?.data?.detail||"Could not assign centre staff.");}};
  const active=async(user)=>{try{await api.patch(`/admin/users/${user.id}/active`,null,{params:{is_active:!user.is_active}});setRefresh(refresh+1);}catch(err){setMessage(err.response?.data?.detail||"Could not update user.");}};
  return <><PageHeader eyebrow="ACCOUNT ADMINISTRATION" title="Users and staff" subtitle="Manage account access and assign verified users to centres."/><section className="panel admin-form-panel"><h2>Assign centre staff</h2><form className="inline-form" onSubmit={assign}><label>Centre<select required value={centreId} onChange={(e)=>setCentreId(e.target.value)}><option value="">Select centre</option>{centres.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>User email<input type="email" required value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="Verified account email"/></label><button className="primary-button">Assign staff</button></form>{message&&<p className="muted">{message}</p>}</section><div className="filter-row"><label className="search-field">⌕<input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search email"/></label></div><section className="panel dashboard-panel"><DataTable columns={[{key:"email",label:"Account"},{key:"full_name",label:"Name"},{key:"role",label:"Role",render:(u)=>pretty(u.role)},{key:"is_active",label:"Access",render:(u)=><span className={`status-pill ${u.is_active?"status-confirmed":"status-cancelled"}`}>{u.is_active?"Active":"Disabled"}</span>},{key:"created_at",label:"Joined",render:(u)=>u.created_at?new Date(u.created_at).toLocaleDateString():"—"},{key:"action",label:"",render:(u)=><button className="text-button" onClick={()=>active(u)}>{u.is_active?"Disable":"Enable"}</button>}]} rows={users} empty="No users found."/></section></>;
}

function BookingsAdmin(){const {items:bookings}=useApi("/admin/bookings?limit=100");const [message,setMessage]=useState("");const complete=async(b)=>{try{await api.patch(`/admin/bookings/${b.id}/complete`);setMessage("Booking marked complete.");window.location.reload();}catch(e){setMessage(e.response?.data?.detail||"Could not update booking.");}};return <><PageHeader eyebrow="OPERATIONS" title="All bookings" subtitle="Review platform appointments and complete eligible visits."/>{message&&<div className="notice error">{message}</div>}<section className="panel dashboard-panel"><DataTable columns={[{key:"id",label:"Reference",render:(b)=>b.id.slice(0,8)},{key:"patient_id",label:"Patient",render:(b)=>b.patient_id.slice(0,8)},{key:"appointment_at",label:"Date & time",render:(b)=>new Date(b.appointment_at).toLocaleString()},{key:"amount",label:"Amount",render:(b)=>money(b.amount)},{key:"status",label:"Status",render:(b)=><span className={`status-pill status-${b.status}`}>{pretty(b.status)}</span>},{key:"action",label:"",render:(b)=>b.status==="confirmed"?<button className="text-button" onClick={()=>complete(b)}>Mark complete</button>:null}]} rows={bookings} empty="No bookings yet."/></section></>;}

function AuditAdmin(){const {items:events}=useApi("/admin/audit/booking-events?limit=200");const {items:webhooks}=useApi("/admin/audit/webhook-events?limit=100");return <><PageHeader eyebrow="AUDIT TRAIL" title="State changes and payment events" subtitle="Review booking transitions and webhook processing history."/><section className="panel dashboard-panel"><div className="section-title"><h2>Booking transitions</h2></div><DataTable columns={[{key:"created_at",label:"Time",render:(e)=>new Date(e.created_at).toLocaleString()},{key:"booking_id",label:"Booking",render:(e)=>e.booking_id.slice(0,8)},{key:"from_status",label:"From",render:(e)=>pretty(e.from_status)},{key:"to_status",label:"To",render:(e)=><b>{pretty(e.to_status)}</b>},{key:"actor_id",label:"Actor",render:(e)=>e.actor_id?.slice(0,8)||"System"},{key:"note",label:"Note"}]} rows={events} empty="No booking events."/></section><section className="panel dashboard-panel"><div className="section-title"><h2>Webhook events</h2></div><DataTable columns={[{key:"created_at",label:"Received",render:(e)=>new Date(e.created_at).toLocaleString()},{key:"event_id",label:"Provider event"},{key:"event_type",label:"Type"},{key:"processed",label:"Applied",render:(e)=>e.processed?"Yes":"No"}]} rows={webhooks} empty="No webhook events."/></section></>;}

function NotificationsAdmin(){const {items,loading,error}=useApi("/admin/notifications?limit=200");return <><PageHeader eyebrow="SYSTEM OPERATIONS" title="Notification outbox" subtitle="Durably queued mock notification jobs and delivery attempts."/>{error&&<div className="notice error">{error}</div>}<section className="panel dashboard-panel"><DataTable columns={[{key:"created_at",label:"Queued",render:(e)=>new Date(e.created_at).toLocaleString()},{key:"event_type",label:"Event"},{key:"status",label:"Status"},{key:"attempts",label:"Attempts"},{key:"last_error",label:"Last error",render:(e)=>e.last_error||"—"}]} rows={items} empty={loading?"Loading…":"No notifications queued."}/></section></>;}
