import { useState } from "react";
import { Link, useLocation } from "react-router-dom";
import api from "../lib/api";
import { useApi } from "../hooks/useApi";
import { DataTable, PageHeader } from "../components/Layout";

const money=(v)=>`₹${Number(v||0).toLocaleString("en-IN")}`;
const pretty=(v)=>v?.replaceAll("_"," ")||"—";

export default function StaffWorkspace(){
  const path=useLocation().pathname;
  const [refresh,setRefresh]=useState(0);
  const {data:summary}=useApi("/staff/overview",refresh);
  const {items:centres,error:centreError}=useApi("/staff/centres",refresh);
  const {items:tests}=useApi("/tests?limit=100");
  const {items:bookings}=useApi("/staff/bookings?limit=100",refresh);
  const [message,setMessage]=useState("");
  const complete=async(booking)=>{try{await api.patch(`/staff/bookings/${booking.id}/complete`);setMessage("Appointment marked complete.");setRefresh(refresh+1);}catch(e){setMessage(e.response?.data?.detail||"Could not update appointment.");}};
  if(path==="/staff/tests") return <><PageHeader eyebrow="CENTRE WORKSPACE" title="Test management" subtitle="Manage the tests and prices offered by your assigned centre."/>{centreError&&<div className="notice error">{centreError}</div>}{centres.length?<Offerings centres={centres} tests={tests} refreshKey={refresh} onRefresh={()=>setRefresh(refresh+1)} setMessage={setMessage}/>:<div className="empty-state"><b>Your account has no centre assignment yet.</b><p>Ask an administrator to assign your account to a diagnostic centre.</p></div>}{message&&<div className="notice success">{message}</div>}</>;
  if(path==="/staff/bookings") return <><PageHeader eyebrow="CENTRE WORKSPACE" title="Centre bookings" subtitle="Review appointments at the centres assigned to your account."/>{message&&<div className="notice success">{message}</div>}<section className="panel dashboard-panel"><DataTable columns={[{key:"id",label:"Reference",render:(b)=>b.id.slice(0,8)},{key:"patient_id",label:"Patient",render:(b)=>b.patient_id.slice(0,8)},{key:"appointment_at",label:"Appointment",render:(b)=>new Date(b.appointment_at).toLocaleString()},{key:"amount",label:"Amount",render:(b)=>money(b.amount)},{key:"status",label:"Status",render:(b)=><span className={`status-pill status-${b.status}`}>{pretty(b.status)}</span>},{key:"action",label:"",render:(b)=>b.status==="confirmed"?<button className="text-button" onClick={()=>complete(b)}>Mark complete</button>:null}]} rows={bookings} empty="No appointments found."/></section></>;
  if(path==="/staff/centres") return <><PageHeader eyebrow="CENTRE WORKSPACE" title="My centre" subtitle="Centre details and service locations assigned to you."/>{centreError&&<div className="notice error">{centreError}</div>}<div className="centre-grid">{centres.map((c)=><article className="panel staff-centre" key={c.id}><span className="metric-icon">⌖</span><p className="eyebrow">{c.city}{c.state?`, ${c.state}`:""}</p><h2>{c.name}</h2><p>{c.address}</p><p>{c.phone||"No phone listed"}</p><div className="service-chips">{(c.services||[]).map((s)=><span key={s}>{s}</span>)}</div><Link className="text-button" to={`/centres/${c.id}`}>View public details →</Link></article>)}</div>{!centres.length&&<div className="empty-state"><b>No centre assigned.</b><p>Ask an EVE administrator to assign your centre.</p></div>}</>;
  if(path==="/staff/reports") return <><PageHeader eyebrow="CENTRE WORKSPACE" title="Reports and activity" subtitle="A quick view of bookings and catalogue activity across your centre."/><div className="metric-grid">{[["⌖","Assigned centres",summary?.centres],["▦","Total bookings",summary?.bookings],["◷","Today's bookings",summary?.today],["✓","Confirmed visits",summary?.confirmed],["✚","Test offerings",summary?.offerings]].map(([icon,label,value])=><Metric key={label} icon={icon} label={label} value={value??"—"}/>)}</div><section className="panel dashboard-panel"><h2>Recent appointments</h2><DataTable columns={[{key:"id",label:"Reference",render:(b)=>b.id.slice(0,8)},{key:"appointment_at",label:"Appointment",render:(b)=>new Date(b.appointment_at).toLocaleString()},{key:"amount",label:"Price",render:(b)=>money(b.amount)},{key:"status",label:"Status",render:(b)=><span className={`status-pill status-${b.status}`}>{pretty(b.status)}</span>}]} rows={bookings.slice(0,20)} empty="No appointments in this reporting period."/></section></>;
  const latest=bookings.slice(0,6);
  return <><PageHeader eyebrow="CENTRE WORKSPACE" title="Centre dashboard" subtitle="Today’s appointments and service activity." action={<Link className="primary-button" to="/staff/tests">Manage tests</Link>}/>{centreError&&<div className="notice error">{centreError}</div>}<div className="metric-grid">{[["▦","Total bookings",summary?.bookings],["◷","Today's bookings",summary?.today],["✓","Confirmed visits",summary?.confirmed],["✚","Test offerings",summary?.offerings]].map(([icon,label,value])=><Metric key={label} icon={icon} label={label} value={value??"—"}/>)}</div><div className="quick-grid staff-shortcuts"><Link className="quick-card" to="/staff/centres"><span>⌖</span><b>My centre</b><small>{centres.length} assigned</small></Link><Link className="quick-card" to="/staff/tests"><span>✚</span><b>Test management</b><small>Pricing and availability</small></Link><Link className="quick-card" to="/staff/bookings"><span>▦</span><b>Bookings</b><small>Patient appointments</small></Link><Link className="quick-card" to="/staff/reports"><span>▤</span><b>Reports</b><small>Centre activity</small></Link></div><section className="panel dashboard-panel"><div className="section-title"><h2>Recent bookings</h2><Link className="subtle-link" to="/staff/bookings">View all →</Link></div><DataTable columns={[{key:"id",label:"Reference",render:(b)=>b.id.slice(0,8)},{key:"patient_id",label:"Patient",render:(b)=>b.patient_id.slice(0,8)},{key:"appointment_at",label:"Date & time",render:(b)=>new Date(b.appointment_at).toLocaleString()},{key:"amount",label:"Amount",render:(b)=>money(b.amount)},{key:"status",label:"Status",render:(b)=><span className={`status-pill status-${b.status}`}>{pretty(b.status)}</span>}]} rows={latest} empty="No appointments yet."/></section></>;
}

function Metric({icon,label,value}){return <article className="metric-card"><span className="metric-icon">{icon}</span><div><small>{label}</small><b>{value}</b></div></article>;}

function Offerings({centres,tests,refreshKey,onRefresh,setMessage}){
  const [centreId,setCentreId]=useState(centres[0]?.id||"");const [testId,setTestId]=useState("");const [price,setPrice]=useState("");
  const {items:offers}=useApi(`/staff/offerings?centre_id=${centreId}&limit=100`,refreshKey);
  const add=async(e)=>{e.preventDefault();try{await api.post("/centre-tests",{centre_id:centreId,test_id:testId,price:Number(price)});setMessage("Test offering added.");setPrice("");onRefresh();}catch(error){setMessage(error.response?.data?.detail||"Could not add test offering.");}};
  const toggle=async(offer)=>{try{await api.patch(`/centre-tests/${offer.id}`,{is_available:!offer.is_available});setMessage("Offering availability updated.");onRefresh();}catch(error){setMessage(error.response?.data?.detail||"Could not update offering.");}};
  const updatePrice=async(offer)=>{const next=window.prompt("New centre price (INR)",String(offer.price));if(next===null)return;try{await api.patch(`/centre-tests/${offer.id}`,{price:Number(next)});setMessage("Price updated.");onRefresh();}catch(error){setMessage(error.response?.data?.detail||"Could not update price.");}};
  return <><section className="panel admin-form-panel"><h2>Add test to this centre</h2><form className="inline-form" onSubmit={add}><label>Centre<select required value={centreId} onChange={(e)=>setCentreId(e.target.value)}>{centres.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Test<select required value={testId} onChange={(e)=>setTestId(e.target.value)}><option value="">Select test</option>{tests.map((t)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Price (INR)<input type="number" min="0.01" step="0.01" required value={price} onChange={(e)=>setPrice(e.target.value)}/></label><button className="primary-button">Add offering</button></form></section><section className="panel dashboard-panel"><div className="section-title"><h2>Centre test offerings</h2></div><DataTable columns={[{key:"test_id",label:"Test",render:(o)=>tests.find((t)=>t.id===o.test_id)?.name||o.test_id.slice(0,8)},{key:"price",label:"Price",render:(o)=>`₹${Number(o.price).toFixed(2)}`},{key:"is_available",label:"Status",render:(o)=><span className={`status-pill ${o.is_available?"status-confirmed":"status-cancelled"}`}>{o.is_available?"Available":"Unavailable"}</span>},{key:"action",label:"",render:(o)=><div className="table-actions"><button className="text-button" onClick={()=>updatePrice(o)}>Change price</button><button className="text-button" onClick={()=>toggle(o)}>{o.is_available?"Pause":"Enable"}</button></div>}]} rows={offers} empty="No offerings yet."/></section></>;
}
